version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ciweda-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/ciweda_db
      SPRING_DATASOURCE_USERNAME: ciweda
      SPRING_DATASOURCE_PASSWORD: adewic_4929

    depends_on:
      - postgis
  postgis:
    image: tobi312/rpi-postgresql-postgis:16-3.4-alpine-arm64
    container_name: postgis
    environment:
      POSTGRES_PASSWORD: adewic_4929
      POSTGRES_USER: ciweda
      POSTGRES_DB: ciweda_db
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
